# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: ["jekyll-paginate", "jekyll/scholar"]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://lprisan.github.io/
# baseurl: /sustain/
title: Luis P. Prieto
author: Luis P. Prieto
description: Professional and personal website
avatar: lprisan.jpg
email: luis.pablo.prieto@gmail.com
github: lprisan # username
#twitter: username
linkedin: lprisan
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-89940273-1


# needed for travis-ci build
exclude: [vendor]
