# top level stuff you probably don't need to touch
highlighter: pygments
# markdown: rdiscount
# rdiscount:
#   extensions: [smart]
permalink: /:title.html
paginate: 5
gems: ["jekyll-paginate"]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://lprisan.github.io/
# baseurl: /sustain/
title: Luis P. Prieto
author: Luis P. Prieto
description: Professional and personal website
avatar: lprisan.jpg
email: luis.pablo.prieto@gmail.com
github: lprisan # username
#twitter: username
linkedin: lprisan
scholar: ySpnj0MAAAAJ
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-89940273-1


# needed for travis-ci build
exclude: [vendor]

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
