---
title: "Other Projects"
---


# Writing

* I am now starting a blog where I write about issues of Ph.D. student productivity, supervision and wellbeing, called [A Happy PhD](https://ahappyphd.org).

# Music

* I sung with [Artenativ](http://www.artenativ.es/), an "a cappella" group based in Valladolid (Spain), doing gospel, jazz, covers of modern songs, musicals, theater... you name it.
* [Sygmalion](https://myspace.com/sygmalion/music/songs), a short-lived solo project featuring more atmospheric pop-rock songs.
* I played keyboards and sung with Sed, a rock band that evolved from the punk-rock of Green Day to the pop of U2 or Coldplay. Most of it has gone offline, but you can still find some songs [here](http://members.tripod.com/sed_mp3/).
* Before that, I also played in several heavy/progressive metal bands in Valladolid, like Mind Traveller, or Istar.

# Photography

* [100 jours en France](http://100joursenfrance.tumblr.com/), a photoblog project I did during my stay in Grenoble, France.
* I used to keep in my [Flickr account](https://www.flickr.com/photos/lprisan/) some of the nicer photos I did, but I don't update it much anymore.
* There are also a few photos in my [Instagram](https://www.instagram.com/lprisan/).
